Although our model currently only incorporates cell-free transmission, since the ABM models interactions of each cell in a culture dish, the spatial aspects of different viral transmission routes can be explored in detail. There has been recent interest in viruses that transmit via cell to cell transmission, with ODE \cite{allen15,komarova13,iwami15}, stochastic \cite{graw15}, and ABM \cite{kumberger18,blahut21} models developed to study how cell to cell transmission alters infection dynamics. There are also viruses that cause cells that form syncytia, which are cells that have fused into a single multi-nucleated cell. Not much is known about how syncytia alter infection dynamics, with a recent ODE model attempting to assess the effect of syncytia on viral time course \cite{jessie21}, but spatial effects really need to be included for a proper assessment of the role of syncytia. Finally, advection can be added to the diffusion of the virus particles to more closely mimic the respiratory tract. Recent PDE \cite{quirouette20} and ODE \cite{gonzalez19} models both indicate that the addition of advection can limit the spread of respiratory viruses towards the lower respiratory tract, but the stochasticity included in an ABM might affect this result. 

While the model is able to replicate a typical viral time course during an infection, it is missing many components that play important roles in the infection. For example, the immune response of the host has not been added to the model. The immune response is a large, if not the main, contributing factor to symptoms experienced during a viral infection \cite{manchanda14,zheng18}, but also limits spread of infection itself \cite{dobrovolny13}. ABMs are already used to model various aspects of the immune response \cite{whitman20,kerepesi19,levin16}, so the immune response can be incorporated into the existing ABM/PDEM framework. Cell tropism, the preference of virus for one cell type over another, is another feature of viral infections that can be incorporated into the ABM. ODE modeling indicates that cell tropism can lead to longer lasting infections \cite{dobrovolny10}, but will also likely affect the spatial dynamics of infection. Finally, variation in production of virus by individual cells \cite{timm12} can be incorporated to determine how this type of cell heterogeneity affects spatiotemporal infection dynamics.

In this paper, we show the use of GPUs to accelerate computation of agent-based and partial-differential equation hybrid models allows for simulation results within hours, but with the necessary level of detail to capture individual cell effects, and allows for parameterizing the model quickly. The model in this work accurately replicates the diffusion of a virus, the stages of infection of individual cells, and can be fit to data within hours. While still lacking some of the biology needed for replication of \emph{in vivo} infections, the speed of computation leaves room for incorporation of additional features. Thus, this model implementation forms the foundation of a modeling and simulation tool that can accurately predict in-host viral dynamics and be quickly deployed to help combat the next pandemic.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

We find infection durations ranging from 37--73 days. Studies suggest that median duration of viral shedding is 14--20 days after symptom onset, with some patients shedding virus for more than 30 days after symptom onset \cite{qi20, he20shed, zhou20, lee20}. One Italian study found a longer median shedding duration of 36 days after symptom onset \cite{mancuso20}. There are, however, cases of patients who have shed virus for longer periods of time, with several case studies finding patients who shed virus for more than 60 days after hospitalization \cite{park20, liu20, li20shed}. In some studies, longer duration of viral shedding is associated with more serious clinical outcomes such as ICU admission or invasive ventilation \cite{zeng20, lee20}, although other studies have noted that asymptomatic patients also seem to shed virus for longer than mildly symptomatic patients \cite{long20}.

Our findings indicating a decrease in AUC, but an increase in viral peak as MOI increases could be viewed as contradictory since both peak viral load and AUC are supposed to be indicators of disease severity. However, disease severity is often ill-defined. One study has shown a correlation between viral load and total symptom score \cite{chen12} and another between nasal discharge and viral load \cite{handel15} for influenza. This implies that a higher peak viral load should lead to higher symptom score, at least around the time of viral peak. Clinical studies, however, tend to use area under the viral curve as an endpoint in studies as an indicator of disease severity \cite{devincenzo20, hershberger19, stevens18, devincenzo15}, perhaps in an attempt to combine both the severity of symptoms and the duration over which symptoms are experienced. This leads back to the question of whether severity should be assessed by the worst period of symptoms, even it is only for a short duration, or whether disease severity should be assessed by milder, but sustained, symptoms.

Viral load on its own is not the only cause of the symptoms experienced by patients. The immune response is thought to underlie many of the symptoms that cause patient discomfort \cite{hijano19} and medical complications \cite{xu19} for other respiratory viruses. A study using the coronavirus that causes Middle East respiratory syndrome found that high viral load was correlated to high levels of inflammatory cytokines that are, in turn, linked to higher mortality \cite{alosaimi20}. Several studies also hypothesize a connection between intensity of the immune response and severe disease for SARS-CoV-2 \cite{lin20,cao20path,zhu20cardio}. For other respiratory infections, there are several studies that link the size of viral inoculum to variations in various components of the immune response \cite{go19, littwitz17, handel18, redeker14, anderson10}. Another study links area under neutrophils curve and area under IL-8 curve to symptom severity in respiratory tract infections \cite{henriquez15}. Unfortunately, our model does not include an immune response, and so cannot investigate how immune response might vary with initial inoculum dose and affect the severity of the infection. While mathematical models that include immune responses \cite{dobrovolny13} and symptoms \cite{canini11,price15} have been examined for other respiratory viral infections, there is currently not enough time course data on SARS-CoV-2 immune responses to properly assess the validity of these models for the novel coronavirus.  

There are other factors that affect whether a large exposure will lead to severe infection. Simulations show that the site of deposition within the respiratory tract affects not only whether an infection takes hold, but also how easily the virus will replicate \cite{haghnegahdar19}. Like other respiratory viruses, SARS-CoV-2 tends to result in more severe infections when it manages to extend to the lower respiratory tract \cite{COVID20}. The ability to spread to the lower respiratory tract seems to be related to mucosal velocity within the respiratory tract \cite{gonzalez19,quirouette20}, and not directly to viral replication, so this is yet another factor that needs to be considered in determining the severity of the infection. Since our model does not spatially reproduce the respiratory tract, we also cannot assess how these factors might alter our predictions of viral time course.

The model used here is fairly generic and simulates SARS-CoV-2 only through choice of parameters. However, the effect of initial inoculum on viral titer has not previously been examined in an ABM of viral dynamics. Previous studies using ordinary differential equation (ODE) models suggest that model structure and underlying assumptions change the predicted dose-response \cite{wethington19, li14}. Interestingly, the ABM is target-cell limited, and draws its parameter values from a fit of a target-cell limited model to SARS-CoV-2 data, but the dose-response trends observed here are quite different from the dose response trends observed with a traditional target-cell limited ODE model \cite{wethington19,li14}. For example, in the target-cell limited ODE, viral titer peak and growth rate do not change with initial inoculum \cite{wethington19, li14}, but the ABM predicts an increase in both. Time of viral peak and infection duration trends for the ABM are similar to those predicted by target-cell limited ODEs \cite{wethington19, li14}.

Despite the limitations of our model, our study found that initial inoculum dose changes the viral time course and that many characteristic features of the viral titer curve change monotonically with the inoculum size. Future studies are needed to extend these results to symptom severity and changes in the immune response to SARS-CoV-2.

